server:
  port: 8083

spring:
  application:
    name: inventoryservice

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # or validate/create/drop depending on env
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
ml:
  service:
    host: ${ML_SERVICE_HOST:localhost}
    port: ${ML_SERVICE_PORT:8000}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

inventory:
  base-url: http://productservice:8082  # Static config to call inventory-service

