apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecomsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nitish757/frontend:5.0.0
        ports:
        - containerPort: 5173
        envFrom:
        - configMapRef:
            name: app-config
