apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecomsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nitish757/frontend:5.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        resources:
         limits:
          cpu: "500m"
          memory: "512Mi"
         requests:
          cpu: "100m"
          memory: "128Mi"
        envFrom:
        - configMapRef:
            name: app-config
