apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecomsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: inventory-service
        image: nitish757/product-service:3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
         limits:
          cpu: "500m"
          memory: "512Mi"
         requests:
          cpu: "100m"
          memory: "128Mi"
        envFrom:
        - configMapRef:
            name: app-config
