apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: ecomsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: mbashish/forecastservice:v3
        ports:
        - containerPort: 8000
