apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecomsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: nitish757/inventory-service:3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        resources:
         limits:
          cpu: "500m"
          memory: "512Mi"
         requests:
          cpu: "100m"
          memory: "128Mi"
        env:
         - name: ML_SERVICE_HOST
           value: "ml-service"
         - name: ML_SERVICE_PORT
           value: "8000"
        envFrom:
        - configMapRef:
            name: app-config
            
