services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mlflow:
    build: .
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri mysql+pymysql://root:root@mysql/mlflow --default-artifact-root /mlruns
    ports:
      - "5000:5000"
    volumes:
      - /home/m_b_ashish/forecastService/mlruns:/mlruns
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
